language: java
jdk:
  - oraclejdk8

notifications:
  email: true
    
deploy:
  provider: releases
  api_key: "e4b4f81aedeaa17bbaaf46237bb05cf2278b1b54"
  file_glob: true
  file: "target/raspigw*.jar"
  skip_cleanup: true
  on:
    tags: true